import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, Navigate, useNavigate } from 'react-router-dom';
import axios from 'axios';
import { LogOut } from 'lucide-react';
import './style.css';

const API = axios.create({ baseURL: '/api' });
const AuthContext = createContext();
const useAuth = () => useContext(AuthContext);
API.interceptors.request.use((config) => { const t = localStorage.getItem('token'); if (t) config.headers.Authorization = `Bearer ${t}`; return config; });

function AuthProvider({ children }) {
  const [user, setUser] = useState(JSON.parse(localStorage.getItem('user') || 'null'));
  const login = (data) => { localStorage.setItem('token', data.token); localStorage.setItem('user', JSON.stringify(data.user)); setUser(data.user); };
  const logout = () => { localStorage.clear(); setUser(null); };
  return <AuthContext.Provider value={{ user, login, logout }}>{children}</AuthContext.Provider>;
}
function Protected({ children }) { return useAuth().user ? children : <Navigate to="/login" />; }
function Layout({ children }) {
  const { user, logout } = useAuth();
  return <><nav><h2>Team Task Manager</h2>{user && <div><Link to="/">Dashboard</Link><Link to="/projects">Projects</Link><Link to="/tasks">Tasks</Link><span>{user.name} ({user.role})</span><button onClick={logout}><LogOut size={16}/>Logout</button></div>}</nav><main>{children}</main></>;
}
function AuthPage({ type }) {
  const [form, setForm] = useState({ name:'', email:'', password:'', role:'Member' });
  const [error, setError] = useState(''); const nav = useNavigate(); const { login } = useAuth();
  async function submit(e){ e.preventDefault(); setError(''); try { const url = type==='login'?'/auth/login':'/auth/signup'; const {data}=await API.post(url,form); login(data); nav('/'); } catch(err){ setError(err.response?.data?.message || err.response?.data?.errors?.[0]?.msg || 'Something went wrong'); }}
  return <div className="auth"><form onSubmit={submit} className="card form"><h1>{type==='login'?'Login':'Signup'}</h1>{error && <p className="error">{error}</p>}{type==='signup'&&<><input placeholder="Name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Member</option><option>Admin</option></select></>}<input placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button>{type==='login'?'Login':'Create Account'}</button><p>{type==='login'?'No account?':'Already registered?'} <Link to={type==='login'?'/signup':'/login'}>{type==='login'?'Signup':'Login'}</Link></p></form></div>;
}
function Dashboard(){ const [stats,setStats]=useState(null); useEffect(()=>{API.get('/dashboard').then(r=>setStats(r.data));},[]); if(!stats)return <p>Loading...</p>; return <><h1>Dashboard</h1><div className="grid">{Object.entries({Projects:stats.projects,Total:stats.total,Todo:stats.todo,'In Progress':stats.inProgress,Completed:stats.completed,Overdue:stats.overdue}).map(([k,v])=><div className="card stat" key={k}><h3>{k}</h3><p>{v}</p></div>)}</div></>}
function Projects(){ const {user}=useAuth(); const [projects,setProjects]=useState([]),[users,setUsers]=useState([]),[form,setForm]=useState({name:'',description:'',members:[]}); const load=()=>API.get('/projects').then(r=>setProjects(r.data)); useEffect(()=>{load(); API.get('/auth/users').then(r=>setUsers(r.data));},[]); async function add(e){e.preventDefault(); await API.post('/projects',form); setForm({name:'',description:'',members:[]}); load();} async function del(id){ if(confirm('Delete project and its tasks?')){await API.delete('/projects/'+id); load();}}
return <><h1>Projects & Team</h1>{user.role==='Admin'&&<form className="card form" onSubmit={add}><h2>Create Project</h2><input placeholder="Project name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><label>Select members</label><select multiple value={form.members} onChange={e=>setForm({...form,members:[...e.target.selectedOptions].map(o=>o.value)})}>{users.map(u=><option key={u._id} value={u._id}>{u.name} - {u.role}</option>)}</select><button>Create Project</button></form>}<div className="list">{projects.map(p=><div className="card" key={p._id}><h2>{p.name}</h2><p>{p.description}</p><p><b>Members:</b> {p.members.map(m=>m.name).join(', ')}</p>{user.role==='Admin'&&<button className="danger" onClick={()=>del(p._id)}>Delete</button>}</div>)}</div></>}
function Tasks(){ const {user}=useAuth(); const [tasks,setTasks]=useState([]),[projects,setProjects]=useState([]),[users,setUsers]=useState([]),[form,setForm]=useState({title:'',description:'',project:'',assignedTo:'',priority:'Medium',dueDate:''}); const load=()=>API.get('/tasks').then(r=>setTasks(r.data)); useEffect(()=>{load(); API.get('/projects').then(r=>setProjects(r.data)); API.get('/auth/users').then(r=>setUsers(r.data));},[]); async function add(e){e.preventDefault(); await API.post('/tasks',form); setForm({title:'',description:'',project:'',assignedTo:'',priority:'Medium',dueDate:''}); load();} async function status(id,s){await API.patch('/tasks/'+id+'/status',{status:s}); load();} async function del(id){if(confirm('Delete task?')){await API.delete('/tasks/'+id);load();}}
return <><h1>Tasks</h1>{user.role==='Admin'&&<form className="card form" onSubmit={add}><h2>Create Task</h2><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select value={form.project} onChange={e=>setForm({...form,project:e.target.value})}><option value="">Choose Project</option>{projects.map(p=><option key={p._id} value={p._id}>{p.name}</option>)}</select><select value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}><option value="">Assign To</option>{users.map(u=><option key={u._id} value={u._id}>{u.name}</option>)}</select><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>Low</option><option>Medium</option><option>High</option></select><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/><button>Create Task</button></form>}<div className="list">{tasks.map(t=><div className="card task" key={t._id}><h2>{t.title}</h2><p>{t.description}</p><p><b>Project:</b> {t.project?.name} | <b>Assigned:</b> {t.assignedTo?.name}</p><p><b>Priority:</b> {t.priority} | <b>Due:</b> {new Date(t.dueDate).toLocaleDateString()}</p><select value={t.status} onChange={e=>status(t._id,e.target.value)}><option>Todo</option><option>In Progress</option><option>Completed</option></select>{user.role==='Admin'&&<button className="danger" onClick={()=>del(t._id)}>Delete</button>}</div>)}</div></>}
function App(){return <AuthProvider><BrowserRouter><Layout><Routes><Route path="/login" element={<AuthPage type="login"/>}/><Route path="/signup" element={<AuthPage type="signup"/>}/><Route path="/" element={<Protected><Dashboard/></Protected>}/><Route path="/projects" element={<Protected><Projects/></Protected>}/><Route path="/tasks" element={<Protected><Tasks/></Protected>}/></Routes></Layout></BrowserRouter></AuthProvider>}
createRoot(document.getElementById('root')).render(<App/>);
